language: go

sudo: required

os:
 - linux

go:
 - "1.9"
 - "1.10"
 - "1.11"
 - master

addons:
 apt:
   packages:
   - oracle-java8-set-default

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq antlr4