language: go

sudo: required
dist: trusty

os:
 - linux

go:
 - "1.9"
 - "1.10"
 - "1.11"
 - master

addons:
 apt:
   packages:
   - oracle-java8-set-default

before_install:
 - sudo add-apt-repository ppa:jonathonf/antlr4
 - sudo apt-get update
 - sudo apt-get install -y antlr4