language: go

sudo: required

os:
 - linux

go:
 - "1.8"
 - "1.9"
 - "1.10"
 - "1.11"
 - master

addons:
 apt:
   packages:
   - oracle-java8-set-default

before_install:
 - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
 - sudo curl -O http://www.antlr.org/download/antlr-4.7.1-complete.jar
 - export CLASSPATH=".:/home/travis/build/christoph2/pyA2L/antlr-4.6-complete.jar:$CLASSPATH"
 - alias antlr4='java -jar /usr/local/lib/antlr-4.7.1-complete.jar'