language: go

sudo: required
dist: trusty

os:
 - linux

go:
 - "1.9"
 - "1.10"
 - "1.11"
 - master

addons:
 apt:
  sources:
   - sourceline: 'deb http://ppa.launchpad.net/jonathonf/antlr4/ubuntu trusty main'
  packages:
   - oracle-java8-set-default
   - antlr4